### PR TITLE
Bump to 2.1-SNAPSHOT

### PR DESCRIPTION
**Pull request by heruan**
Bump main version to 2.1-SNAPSHOT

### CODE REVIEW

**Review by mcollovati — CHANGES_REQUESTED** [review]
Should `version` in `observability-kit-starter/package.json` be updated as well?

There's also a mention to 2.0-SNAPSHOT in `observability-kit-agent/doc/ProjectSetup.asciidoc`

**Comment by mcollovati** [comment]
BTW, in the README it is mentioned that the kit is compatible with Vaadin starting from version 23.2.0.
Should we update it for 2.0 and 2.1 to state that the supported version is Vaadin 24?

**Comment by heruan** [comment]
> Should `version` in `observability-kit-starter/package.json` be updated as well?

Good catch. Do we even need the version there? We're not really publishing the package 🤔 

> There's also a mention to 2.0-SNAPSHOT in `observability-kit-agent/doc/ProjectSetup.asciidoc`

That directory has been handing there since the initial project, by now it should have been all moved to the docs repo. I'll check on this and if it's confirmed, I'll remove the directory 🧹 

> BTW, in the README it is mentioned that the kit is compatible with Vaadin starting from version 23.2.0.
> Should we update it for 2.0 and 2.1 to state that the supported version is Vaadin 24?

We should, yes. I'll create a separate PR for that so we can backport it to the 2.0 branch.

**Comment by heruan** [comment]
I've removed the version from `package.json` and bumped the one in `ProjectSetup.asciidoc` (for now, we'll remove those later).

About the README, it stated the kit is compatible starting with V24 which is still true for 1.0, we'll specify that 2.0 required V24 in the release notes.

**Review by mcollovati — APPROVED** [review]

**Pull request merged**
