### PR TITLE
Jdk21 upgrade

### PR DESCRIPTION
**Pull request by vesanieminen**
## Description

Updated Observability Kit to use:
- JDK 21
- OpenTelemetry 1.31.0
- ByteBuddy 1.15.0

Fixes # (issue)

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

**Comment by vesanieminen** [comment]
The following test fails even on the main branch without my commits so it's not about this PR itself:

```
[INFO] Reactor Summary for observability-kit 3.0-SNAPSHOT:
[INFO] 
[INFO] observability-kit .................................. SUCCESS [  0.521 s]
[INFO] observability-kit-agent ............................ SUCCESS [  5.754 s]
[INFO] observability-kit-starter .......................... SUCCESS [  2.270 s]
[INFO] observability-kit-test ............................. SUCCESS [  0.005 s]
[INFO] observability-kit-agent-it ......................... FAILURE [ 12.617 s]
[INFO] Observability Kit demo application ................. SKIPPED
[INFO] observability-kit-starter-hilla .................... SKIPPED
[INFO] Observability Kit demo application for Hilla ....... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  21.316 s
[INFO] Finished at: 2024-10-17T11:28:48+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project observability-kit-agent-it: Compilation failure
[ERROR] /Users/vesanieminen/code/observability-kit-original/observability-kit-test/observability-kit-agent-it/src/test/java/com/vaadin/observability/test/MainViewIT.java:[91,59] cannot access com.vaadin.testbench.HasLabelAsText
[ERROR]   class file for com.vaadin.testbench.HasLabelAsText not found
```

**Comment by heruan** [comment]
Did we change the JDK baseline in platform from 17 to 21?

**Comment by vesanieminen** [comment]
Good point. I'll check if I can use Java 17 version of Observability Kit using the updated dependencies only with an app running on Java 21. That should be mergeable at least.

**Comment by vesanieminen** [comment]
I tested that downgrading Observability Kit back to Java 17 still works on a Java 21 project. Here's a new PR for that: https://github.com/vaadin/observability-kit/pull/263

**Pull request closed without merging**
